COMPILER = g++
OPTIONS = -std=c++17 -Wall --pedantic-errors

TARGET = program

SRC_EXT = .cc
SRC_DIR = .
SRCS = $(wildcard $(SRC_DIR)/*$(SRC_EXT))

HEADER_DIR = $(SRC_DIR)
HEADER_EXT = .h
HEADER = $(HEADER_DIR)/%$(HEADER_EXT)
HEADERS = $(wildcard $(HEADER_DIR)/*$(HEADER_EXT))
PRECOMPILED_HEADER_EXT = .gch
PRECOMPILED_HEADER = $(HEADER_DIR)/%$(HEADER_EXT)$(PRECOMPILED_HEADER_EXT)
PRECOMPILED_HEADERS = $(addsuffix $(PRECOMPILED_HEADER_EXT), $(HEADERS))

.PHONY: run
run: $(TARGET)
	./$(TARGET) $(ARGS)

.PHONY: build
build: $(TARGET)

.PHONY: clean
clean:
	rm -f $(TARGET)
	rm -f $(PRECOMPILED_HEADERS)

$(TARGET): $(PRECOMPILED_HEADERS) $(SRCS)
	$(COMPILER) $(OPTIONS) -o $@ $(SRCS)

$(PRECOMPILED_HEADER): $(HEADER)
	$(COMPILER) $(OPTIONS) -x c++-header -o $@ $^
